name: BPF Verification Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  bpf-verification:
    strategy:
      fail-fast: false
      matrix:
        insn: [BPF_AND, BPF_JSLT]
        kernel: [5.9]
        spec: ["no-weak-spec", "weak-spec"]
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
            python3 python3-pip \
            libjsoncpp-dev \
            libz3-dev

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          cd bpf-verification
          pip install .

      - name: Verify ${{ matrix.insn }} on v${{ matrix.kernel }}
        id: bpf-verification
        run: |
          mkdir results
          cd bpf-verification
          python3 src/bpf_alu_jmp_synthesis.py --${{ matrix.spec }} \
            --kernver ${{ matrix.kernel }} \
            --encodings_path ../bpf-encodings/${{ matrix.kernel }}/ \
            --res_path ../results \
            --ver_set ${{ matrix.insn }}

      - name: Upload artifacts
        if: ${{ always() }} && steps.bpf-verification.outcome != 'skipped'
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: results-${{ matrix.kernel }}-${{ matrix.insn }}-${{ matrix.spec }}
          path: results/${{ matrix.kernel }}_res
